# Generated by Django 5.2.6 on 2025-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=5000)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
