# Generated by Django 5.2.6 on 2025-09-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_alter_bio_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
