# Generated by Django 5.2.6 on 2025-10-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_alter_bio_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
