# Generated by Django 6.0 on 2026-01-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_alter_bio_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
