# Generated by Django 6.0 on 2026-01-08 13:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_alter_bio_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cv/'),
        ),
    ]
