# Generated by Django 6.0 on 2026-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0007_alter_bio_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='cv',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
