# Generated by Django 5.2.6 on 2025-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
