# Generated by Django 5.2.8 on 2025-12-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='media.production'),
        ),
    ]
