# Generated by Django 6.0 on 2025-12-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_production_media_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('production', 'Production'), ('personality', 'Personality')], default='production', max_length=20),
        ),
    ]
